name: pba
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pillow=8.4.0
  - pip
  - python=3.8.12
  - statsmodels=0.12.1
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - pip:
    - setuptools
    - SimpleITK
    - itk-elastix
    - imageio
    - ipython
    - json5
    - jupyterlab
    - matplotlib
    - notebook
    - opencv-python
    - pandas
    - pyyaml
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboard
    - tqdm
    - seaborn
    - jupyter
    - nibabel

