name: pba
channels:
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - pillow=8.4.0
  - pip=21.2.4
  - python=3.8.12
  - statsmodels=0.12.1
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - pip:
    - setuptools
    - SimpleITK
    - itk-elastix
    - intensity-normalization[ants]
    - huggingface-hub
    - imageio
    - ipython
    - json5
    - jupyterlab
    - matplotlib
    - notebook
    - opencv-python
    - pandas
    - pyyaml
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboard
    - tqdm
    - seaborn
    - jupyter
    - wandb

