!!python/object:argparse.Namespace
aux_optim: !!python/object:argparse.Namespace
  amsgrad: true
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0001
  optimizer: Adam
  weight_decay: 0.0
data: !!python/object:argparse.Namespace
  dataroot: /media/sda/Anna/brain_age/pytorch/data/2d_256/
  dataset: BRAINS
  label_min_max:
  - 0
  - 32
  num_classes: 1
  num_workers: 64
  seed: 2000
  std: 95.08
  testdata: ./dataset/brains_37/test_healthy256_37_new.csv
  traindata: ./dataset/brains_37/train_balanced256_37_new.csv
diffusion: !!python/object:argparse.Namespace
  apply_aux_cls: true
  aux_cls: !!python/object:argparse.Namespace
    arch: resnet50_ckpt
    joint_train: true
    logging_interval: 10
    n_pretrain_epochs: 15
    pre_train: true
  beta_end: 0.02
  beta_schedule: linear
  beta_start: 0.0001
  include_guidance: true
  noise_prior: false
  nonlinear_guidance: !!python/object:argparse.Namespace
    apply_early_stopping: true
    delta: 0
    patience: 50
  num_figs: 10
  test_timesteps: 250
  timesteps: 1000
  vis_step: 100
model: !!python/object:argparse.Namespace
  arch: resnet50
  cat_x: true
  cat_y_pred: true
  data_dim: 150528
  ema: true
  ema_rate: 0.9999
  feature_dim: 6144
  hidden_dim: 6144
  n_input_channels: 3
  n_input_padding: 0
  type: simple
  var_type: fixedlarge
optim: !!python/object:argparse.Namespace
  amsgrad: true
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.001
  lr_schedule: true
  min_lr: 0.0
  optimizer: Adam
  weight_decay: 0.0
sampling: !!python/object:argparse.Namespace
  batch_size: 8
  image_folder: sampling_image_samples
  last_only: true
  sampling_size: 1000
testing: !!python/object:argparse.Namespace
  PICP_range:
  - 2.5
  - 97.5
  batch_size: 8
  compute_metric_all_steps: false
  fig_size:
  - 8
  - 5
  image_folder: testing_image_samples
  last_only: true
  make_plot: true
  metrics_t: 0
  n_bins: 10
  n_samples: 100
  plot_freq: 200
  plot_gen: true
  plot_true: true
  sampling_size: 1000
  squared_plot: true
  trimmed_mean_range:
  - 0.0
  - 30.0
  ttest_alpha: 0.05
training: !!python/object:argparse.Namespace
  add_t0_loss: false
  batch_size: 8
  image_folder: training_image_samples
  lambda_ce: 0.01
  logging_freq: 1200
  n_ce_epochs_interval: 50
  n_ce_epochs_warmup: 10
  n_epochs: 500
  n_minibatches_add_ce: 20
  n_sanity_check_epochs_freq: 500
  n_steps_req_grad: 100
  snapshot_freq: 1000000000
  validation_freq: 5
  warmup_epochs: 20
