data:
    dataset: "BRAINS"
    seed: 2000
    label_min_max: [0, 32]
    num_classes: 1
    num_workers: 64
    dataroot: '/media/sda/Anna/brain_age/pytorch/data/2d_256/'
    traindata: './dataset/brains_75/train_balanced256_75.csv'
    testdata:  './dataset/brains_75/val_balanced256_75.csv'
    std: 95.08
    
model:
    type: "simple"
    data_dim: 150528
    #data_dim: 442368
    #data_dim: [3, 32, 32]
    n_input_channels: 3
    n_input_padding: 0
    feature_dim: 6144
    hidden_dim: 6144
    cat_x: True
    cat_y_pred: True
    arch: resnet50
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: linear  # cosine_anneal, cosine
    beta_start: 0.0001
    beta_end: 0.02
    timesteps: 1000
    test_timesteps: 250
    vis_step: 100
    num_figs: 10
    include_guidance: True  # concat y_t with aux pred as eps_theta input
    apply_aux_cls: True
    #trained_aux_cls_ckpt_path: "/data/classification/pretrained/cifar10_ckpt"
#    trained_aux_cls_ckpt_name: "snapshot_supervised.ckpt"
    #trained_aux_cls_ckpt_name: "snapshot_self_supervised.ckpt"
    aux_cls:
        arch: resnet50_ckpt  # lenet5
        pre_train: True
        joint_train: True
        n_pretrain_epochs: 15 #15
        logging_interval: 10
    nonlinear_guidance:
        apply_early_stopping: True
        patience: 50
        delta: 0  # hyperparameter for improvement measurement in the early stopping scheme

    
training:
    batch_size: 8
    n_epochs: 500
    warmup_epochs: 20
    add_t0_loss: False
    n_steps_req_grad: 100
    n_minibatches_add_ce: 20
    n_ce_epochs_warmup: 10 #10
    n_ce_epochs_interval: 50
    n_sanity_check_epochs_freq: 500
    snapshot_freq: 1000000000
    logging_freq: 1200
    validation_freq: 5
    lambda_ce: 0.01
    image_folder: 'training_image_samples'

sampling:
    batch_size: 8 #64
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 8 #64
    sampling_size: 1000
    last_only: True
    plot_freq: 200
    image_folder: 'testing_image_samples'
    n_samples: 100
    n_bins: 10
    compute_metric_all_steps: False
    metrics_t: 0
    ttest_alpha: 0.05
    trimmed_mean_range: [0.0, 30.0]
    PICP_range: [2.5, 97.5]
    make_plot: True
    squared_plot: True
    plot_true: True
    plot_gen: True
    fig_size: [8, 5]

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0
    lr_schedule: True
    min_lr: 0.0

aux_optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0

